/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIHAB
 */
public class EasyQuestion extends javax.swing.JFrame {

    /**
     * Creates new form Question
     */
    public EasyQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Q1 = new javax.swing.JPanel();
        q1panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Q2 = new javax.swing.JPanel();
        q2panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Q3 = new javax.swing.JPanel();
        q3panel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jButton12 = new javax.swing.JButton();
        Q4 = new javax.swing.JPanel();
        q4panel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jButton13 = new javax.swing.JButton();
        Q5 = new javax.swing.JPanel();
        q5panel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jButton14 = new javax.swing.JButton();
        Q6 = new javax.swing.JPanel();
        q6panel = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jButton15 = new javax.swing.JButton();
        Q7 = new javax.swing.JPanel();
        q7panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        Q8 = new javax.swing.JPanel();
        q8panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jButton17 = new javax.swing.JButton();
        Q9 = new javax.swing.JPanel();
        q9panel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        Q10 = new javax.swing.JPanel();
        q10panel = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jButton19 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 735));
        setPreferredSize(new java.awt.Dimension(735, 735));
        setResizable(false);

        jPanel1.setLayout(null);

        jPanel2.setLayout(new java.awt.CardLayout());

        q1panel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Q1. Where did Harry Potter go to school?");

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Neverland");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Hogwarts");

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Mordor");

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Dreamland");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q1panelLayout = new javax.swing.GroupLayout(q1panel);
        q1panel.setLayout(q1panelLayout);
        q1panelLayout.setHorizontalGroup(
            q1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q1panelLayout.createSequentialGroup()
                .addGroup(q1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q1panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(q1panelLayout.createSequentialGroup()
                        .addGroup(q1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(q1panelLayout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addGroup(q1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        q1panelLayout.setVerticalGroup(
            q1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q1panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton1)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton2)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton3)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Q1Layout = new javax.swing.GroupLayout(Q1);
        Q1.setLayout(Q1Layout);
        Q1Layout.setHorizontalGroup(
            Q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q1panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q1Layout.setVerticalGroup(
            Q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q1panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q1, "card2");

        q2panel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Q2. What is Littlefinger's real name?");

        jRadioButton5.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Jon Arryn");

        jRadioButton6.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Pyat Pree");

        jRadioButton7.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Brynden Tully");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Petyr Baelish");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("PREV");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q2panelLayout = new javax.swing.GroupLayout(q2panel);
        q2panel.setLayout(q2panelLayout);
        q2panelLayout.setHorizontalGroup(
            q2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q2panelLayout.createSequentialGroup()
                .addGroup(q2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q2panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(q2panelLayout.createSequentialGroup()
                        .addGroup(q2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(q2panelLayout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addGroup(q2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );
        q2panelLayout.setVerticalGroup(
            q2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q2panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton5)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton6)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton7)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(q2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Q2Layout = new javax.swing.GroupLayout(Q2);
        Q2.setLayout(Q2Layout);
        Q2Layout.setHorizontalGroup(
            Q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q2panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q2Layout.setVerticalGroup(
            Q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q2panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q2, "card3");

        q3panel.setBackground(new java.awt.Color(0, 0, 0));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Q3. What is the surename of Phoebe from Series F.R.I.E.N.D.S?");

        jRadioButton9.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("Bing");

        jRadioButton10.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("Geller");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jRadioButton11.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("Buffay");

        jRadioButton12.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("Hannigan");

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("PREV");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q3panelLayout = new javax.swing.GroupLayout(q3panel);
        q3panel.setLayout(q3panelLayout);
        q3panelLayout.setHorizontalGroup(
            q3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q3panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(q3panelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(q3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton11)
                    .addGroup(q3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        q3panelLayout.setVerticalGroup(
            q3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q3panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton9)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton10)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton11)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(q3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Q3Layout = new javax.swing.GroupLayout(Q3);
        Q3.setLayout(Q3Layout);
        Q3Layout.setHorizontalGroup(
            Q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q3panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q3Layout.setVerticalGroup(
            Q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q3panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q3, "card4");

        q4panel.setBackground(new java.awt.Color(0, 0, 0));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Q4. How do Anna and Elsa know each other in Frozen?");

        jRadioButton13.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup4.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("Neighbors");

        jRadioButton14.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("Friends");

        jRadioButton15.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup4.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("Sisters");

        jRadioButton16.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup4.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("Cousins");

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("PREV");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q4panelLayout = new javax.swing.GroupLayout(q4panel);
        q4panel.setLayout(q4panelLayout);
        q4panelLayout.setHorizontalGroup(
            q4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q4panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(q4panelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(q4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(q4panelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );
        q4panelLayout.setVerticalGroup(
            q4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q4panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton13)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton14)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton15)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(q4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Q4Layout = new javax.swing.GroupLayout(Q4);
        Q4.setLayout(Q4Layout);
        Q4Layout.setHorizontalGroup(
            Q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q4panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q4Layout.setVerticalGroup(
            Q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q4panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q4, "card5");

        q5panel.setBackground(new java.awt.Color(0, 0, 0));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Q5. Who was the main villain in Avengers: Infinity War?");

        jRadioButton17.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup5.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton17.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setText("Ronan");

        jRadioButton18.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup5.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton18.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setText("Thanos");

        jRadioButton19.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup5.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton19.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setText("Malekith");

        jRadioButton20.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup5.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton20.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton20.setText("Nebula");

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("PREV");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q5panelLayout = new javax.swing.GroupLayout(q5panel);
        q5panel.setLayout(q5panelLayout);
        q5panelLayout.setHorizontalGroup(
            q5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q5panelLayout.createSequentialGroup()
                .addGroup(q5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q5panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(q5panelLayout.createSequentialGroup()
                        .addGroup(q5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(q5panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(q5panelLayout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addGroup(q5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton18)
                                    .addComponent(jRadioButton17)
                                    .addComponent(jRadioButton19)
                                    .addComponent(jRadioButton20))))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        q5panelLayout.setVerticalGroup(
            q5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q5panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton17)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton18)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton19)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(q5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Q5Layout = new javax.swing.GroupLayout(Q5);
        Q5.setLayout(Q5Layout);
        Q5Layout.setHorizontalGroup(
            Q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q5panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q5Layout.setVerticalGroup(
            Q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q5panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q5, "card6");

        q6panel.setBackground(new java.awt.Color(0, 0, 0));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Next");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Q6.Who plays the Joker in The Dark Knight? ");

        jRadioButton21.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup6.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton21.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton21.setText("Jake Gyllenhaal");

        jRadioButton22.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup6.add(jRadioButton22);
        jRadioButton22.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton22.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton22.setText("Heath ledger");

        jRadioButton23.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup6.add(jRadioButton23);
        jRadioButton23.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton23.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton23.setText("Pete Holmes");

        jRadioButton24.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup6.add(jRadioButton24);
        jRadioButton24.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton24.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton24.setText("Joaquin Phoenix");

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("PREV");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q6panelLayout = new javax.swing.GroupLayout(q6panel);
        q6panel.setLayout(q6panelLayout);
        q6panelLayout.setHorizontalGroup(
            q6panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q6panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(q6panelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 190, Short.MAX_VALUE))
            .addGroup(q6panelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(q6panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton22, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton21, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton23, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton24, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        q6panelLayout.setVerticalGroup(
            q6panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q6panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addComponent(jRadioButton21)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton22)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton23)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(q6panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Q6Layout = new javax.swing.GroupLayout(Q6);
        Q6.setLayout(Q6Layout);
        Q6Layout.setHorizontalGroup(
            Q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q6panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q6Layout.setVerticalGroup(
            Q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q6panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q6, "card7");

        q7panel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Q7. Who directed the movie \"Inception\"?");

        jRadioButton25.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(jRadioButton25);
        jRadioButton25.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton25.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton25.setText("Paul Thomas Anderson");

        jRadioButton26.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(jRadioButton26);
        jRadioButton26.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton26.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton26.setText("Quentin Tarantino");

        jRadioButton27.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(jRadioButton27);
        jRadioButton27.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton27.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton27.setText("Martin Scorsese");

        jRadioButton28.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup7.add(jRadioButton28);
        jRadioButton28.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton28.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton28.setText("Christopher Nolan");

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Next");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("PREV");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q7panelLayout = new javax.swing.GroupLayout(q7panel);
        q7panel.setLayout(q7panelLayout);
        q7panelLayout.setHorizontalGroup(
            q7panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q7panelLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 254, Short.MAX_VALUE))
            .addGroup(q7panelLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(q7panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton25)
                    .addComponent(jRadioButton26, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton27, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton28, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q7panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        q7panelLayout.setVerticalGroup(
            q7panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q7panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton25)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton26)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton27)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(q7panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Q7Layout = new javax.swing.GroupLayout(Q7);
        Q7.setLayout(Q7Layout);
        Q7Layout.setHorizontalGroup(
            Q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q7panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q7Layout.setVerticalGroup(
            Q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q7panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q7, "card8");

        q8panel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Q8. What is the name of Jack Sparrow's ship?");

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Next");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jRadioButton29.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup8.add(jRadioButton29);
        jRadioButton29.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton29.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton29.setText("Jolly Roger");
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });

        jRadioButton30.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup8.add(jRadioButton30);
        jRadioButton30.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton30.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton30.setText("Adventure Galley");

        jRadioButton31.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup8.add(jRadioButton31);
        jRadioButton31.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton31.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton31.setText("Black Pearl");

        jRadioButton32.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup8.add(jRadioButton32);
        jRadioButton32.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton32.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton32.setText("CSS Alabama");
        jRadioButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton32ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("PREV");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q8panelLayout = new javax.swing.GroupLayout(q8panel);
        q8panel.setLayout(q8panelLayout);
        q8panelLayout.setHorizontalGroup(
            q8panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q8panelLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q8panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(q8panelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(q8panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton32)
                    .addComponent(jRadioButton31)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton29))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        q8panelLayout.setVerticalGroup(
            q8panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q8panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton29)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton30)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton31)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(q8panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Q8Layout = new javax.swing.GroupLayout(Q8);
        Q8.setLayout(Q8Layout);
        Q8Layout.setHorizontalGroup(
            Q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q8panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q8Layout.setVerticalGroup(
            Q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q8panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q8, "card9");

        q9panel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Q9. Who played Cooper in Interstellar?");

        jRadioButton33.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup9.add(jRadioButton33);
        jRadioButton33.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton33.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton33.setText("Matthew McConaughey");

        jRadioButton34.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup9.add(jRadioButton34);
        jRadioButton34.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton34.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton34.setText("Jason Statham");

        jRadioButton35.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup9.add(jRadioButton35);
        jRadioButton35.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton35.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton35.setText("Woody Harrelson");

        jRadioButton36.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup9.add(jRadioButton36);
        jRadioButton36.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton36.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton36.setText("Jake Gyllenhaal");

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Next");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("PREV");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q9panelLayout = new javax.swing.GroupLayout(q9panel);
        q9panel.setLayout(q9panelLayout);
        q9panelLayout.setHorizontalGroup(
            q9panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q9panelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 242, Short.MAX_VALUE))
            .addGroup(q9panelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(q9panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton36)
                    .addComponent(jRadioButton35)
                    .addComponent(jRadioButton34)
                    .addComponent(jRadioButton33))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q9panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        q9panelLayout.setVerticalGroup(
            q9panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q9panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel10)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton33)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton34)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton35)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(q9panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Q9Layout = new javax.swing.GroupLayout(Q9);
        Q9.setLayout(Q9Layout);
        Q9Layout.setHorizontalGroup(
            Q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q9panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q9Layout.setVerticalGroup(
            Q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q9panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q9, "card10");

        q10panel.setBackground(new java.awt.Color(0, 0, 0));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Finish");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Algerian", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Q10. Who is main character from \"How I Met Your Mother\"?");

        jRadioButton37.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup10.add(jRadioButton37);
        jRadioButton37.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton37.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton37.setText("Robin Scherbatsky");

        jRadioButton38.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup10.add(jRadioButton38);
        jRadioButton38.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton38.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton38.setText("Ted Mosby");

        jRadioButton39.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup10.add(jRadioButton39);
        jRadioButton39.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton39.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton39.setText("Marshall Eriksen");

        jRadioButton40.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup10.add(jRadioButton40);
        jRadioButton40.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jRadioButton40.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton40.setText("\tBarney Stinson");

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("PREV");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q10panelLayout = new javax.swing.GroupLayout(q10panel);
        q10panel.setLayout(q10panelLayout);
        q10panelLayout.setHorizontalGroup(
            q10panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q10panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(q10panelLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(q10panelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(q10panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton40)
                    .addComponent(jRadioButton39)
                    .addComponent(jRadioButton38)
                    .addComponent(jRadioButton37))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        q10panelLayout.setVerticalGroup(
            q10panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q10panelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton37)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton38)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton39)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addGroup(q10panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Q10Layout = new javax.swing.GroupLayout(Q10);
        Q10.setLayout(Q10Layout);
        Q10Layout.setHorizontalGroup(
            Q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q10panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Q10Layout.setVerticalGroup(
            Q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q10panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Q10, "card11");

        jPanel1.add(jPanel2);
        jPanel2.setBounds(430, 80, 700, 580);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MovieQuestion background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1150, 735));
        jLabel1.setMinimumSize(new java.awt.Dimension(1150, 735));
        jLabel1.setPreferredSize(new java.awt.Dimension(735, 735));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q2panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q3panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q4panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
       
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q5panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q6panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q7panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q8panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q9panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton32ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q10panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       movieFristLevelCompleted1 lc1 = new movieFristLevelCompleted1();
       lc1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q1panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q2panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q3panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q4panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q5panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q6panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q7panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q8panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        Q1.removeAll();
        Q1.repaint();
        Q1.revalidate();
        Q1.add(q9panel);
        Q1.repaint();
        Q1.revalidate();
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Q1;
    private javax.swing.JPanel Q10;
    private javax.swing.JPanel Q2;
    private javax.swing.JPanel Q3;
    private javax.swing.JPanel Q4;
    private javax.swing.JPanel Q5;
    private javax.swing.JPanel Q6;
    private javax.swing.JPanel Q7;
    private javax.swing.JPanel Q8;
    private javax.swing.JPanel Q9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JPanel q10panel;
    private javax.swing.JPanel q1panel;
    private javax.swing.JPanel q2panel;
    private javax.swing.JPanel q3panel;
    private javax.swing.JPanel q4panel;
    private javax.swing.JPanel q5panel;
    private javax.swing.JPanel q6panel;
    private javax.swing.JPanel q7panel;
    private javax.swing.JPanel q8panel;
    private javax.swing.JPanel q9panel;
    // End of variables declaration//GEN-END:variables
}
